services:
  - type: web
    name: soundshift-app
    env: python-3.11.7
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 5000